services:
  web:
    build: .
    container_name: dnt-django
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - nginx-proxy-manager_default
      - dnt_network
  db:
    image: postgres:16
    container_name: dnt-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - dnt_network


networks:
  dnt_network:
  nginx-proxy-manager_default:
    external: true