# Generated by Django 5.1.6 on 2025-03-09 15:20

import apps.modules.services.models_functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата записи')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время записи')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPhoto',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.basemodel')),
                ('image', models.ImageField(upload_to='', verbose_name='фотография с приема')),
            ],
            bases=('modules.basemodel',),
        ),
        migrations.CreateModel(
            name='BaseIndexModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.basemodel')),
                ('value', models.IntegerField(verbose_name='результат вычисления индекса')),
            ],
            bases=('modules.basemodel',),
        ),
        migrations.CreateModel(
            name='TeethFormulaModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.basemodel')),
                ('teeth', models.JSONField(default=apps.modules.services.models_functions.get_teeth_dict, verbose_name='json с буквой каждого зуба')),
            ],
            bases=('modules.basemodel',),
        ),
        migrations.CreateModel(
            name='IndexCPITN',
            fields=[
                ('baseindexmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.baseindexmodel')),
            ],
            bases=('modules.baseindexmodel',),
        ),
        migrations.CreateModel(
            name='IndexCPU',
            fields=[
                ('baseindexmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.baseindexmodel')),
            ],
            bases=('modules.baseindexmodel',),
        ),
        migrations.CreateModel(
            name='IndexOHIS',
            fields=[
                ('baseindexmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.baseindexmodel')),
            ],
            bases=('modules.baseindexmodel',),
        ),
        migrations.CreateModel(
            name='IndexPI',
            fields=[
                ('baseindexmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.baseindexmodel')),
            ],
            bases=('modules.baseindexmodel',),
        ),
        migrations.CreateModel(
            name='IndexPMA',
            fields=[
                ('baseindexmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.baseindexmodel')),
            ],
            bases=('modules.baseindexmodel',),
        ),
    ]
