# Generated by Django 5.1.6 on 2025-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseindexmodel',
            name='value',
            field=models.FloatField(verbose_name='результат вычисления индекса'),
        ),
    ]
