# Generated by Django 5.1.6 on 2025-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, verbose_name='имя')),
                ('last_name', models.CharField(max_length=500, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=500, verbose_name='отчество')),
                ('birthdate', models.DateField(verbose_name='дата рождения')),
                ('other_info', models.TextField(verbose_name='общая информация')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
        ),
    ]
